# Generated by Django 6.0.4 on 2026-04-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_recurringtask_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
